# Generated by Django 2.1.7 on 2019-02-19 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_make_non_required_fields_nullable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('cart', 'product_id')},
        ),
    ]
